---
title: "Supplementary Materials"
description:
author:
  - name: Mikołaj Biesaga and Szymon Talaga
    affiliation: The Robert Zajonc Institute for Social Studies
    affiliation_url: www.iss.uw.edu.pl/en/
date: "`r Sys.Date()`"
output: radix::radix_article
---

## 2. Method

```{r setup_env, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, message = FALSE, warning = FALSE, fig.width = 8, fig.asp = 1)
```

```{r setup}
library(magrittr)
library(tidyverse)
library(reticulate)
library(lattice)
library(zoo)
library(MuMIn)
library(acss)
library(haven)
library(nlme)
library(kableExtra)
source("helpers/helpers.R")
## Ustaw temat ggplot()
theme_set(theme_classic())
## Środowisko Conda
use_condaenv("bdm")
```

```{r load_and_prepare_data}
## Wczytanie danych z wyniki_new.csv
data <- read_delim("data/Study_1.csv", delim = ";") %>%
    rename_at(vars(matches("^\\d")), ~str_c("d", .x)) %>%
    mutate_at(vars(matches("^d\\d")), as.integer) %>%
    rename(id = X)

## Zamiana na format long
data_long <- gather(data, key = "Index", value = "Bit", matches("^d\\d")) %>%
    filter(!is.na(Bit)) %>%
    arrange(id) %>%
    group_by(id) %>% 
    mutate(idx = 1:n()) %>%
    filter(idx < 313) %>%
    summarize(seq = list(Bit)) %>%
    ungroup 
``` 

### Study 1.

```{python prepare_strings}
import numpy as np
import pandas as pd
from pybdm import BDM
from pybdm import PartitionIgnore, PartitionRecursive

def window_bdm(seq, bdm, k=9):
    return np.array([ bdm.bdm(seq[i:(i+k)]) for i in range(len(seq) - k) ])
    
data = r.data_long
data.id = data.id.astype(int)
data.seq = data.seq.apply(lambda x: np.array(x, dtype=int))
bdm_ignore = BDM(ndim=1, partition=PartitionIgnore)

bdm_recursive_9 = BDM(ndim=1, partition=PartitionRecursive, min_length=9)
seq9 = pd.DataFrame({'id': r.data_long.id.astype(int),
                     'cmx': data.seq.apply(bdm_ignore.nbdm),
                     'cmx_w': data.seq.apply(lambda x: window_bdm(x, bdm_recursive_9, k = 9))})


bdm_recursive_7 = BDM(ndim=1, partition=PartitionRecursive, min_length=7)
seq7 = pd.DataFrame({'id': r.data_long.id.astype(int),
                     'cmx': data.seq.apply(bdm_ignore.nbdm),
                     'cmx_w': data.seq.apply(lambda x: window_bdm(x, bdm_recursive_7, k = 7))})
                     
bdm_recursive_8 = BDM(ndim=1, partition=PartitionRecursive, min_length=8)
seq8 = pd.DataFrame({'id': r.data_long.id.astype(int),
                     'cmx': data.seq.apply(bdm_ignore.nbdm),
                     'cmx_w': data.seq.apply(lambda x: window_bdm(x, bdm_recursive_8, k = 8))})
                     
bdm_recursive_6 = BDM(ndim=1, partition=PartitionRecursive, min_length=6)
seq6 = pd.DataFrame({'id': r.data_long.id.astype(int),
                     'cmx': data.seq.apply(bdm_ignore.nbdm),
                     'cmx_w': data.seq.apply(lambda x: window_bdm(x, bdm_recursive_6, k = 6))})
                     
bdm_recursive_5 = BDM(ndim=1, partition=PartitionRecursive, min_length=5)
seq5 = pd.DataFrame({'id': r.data_long.id.astype(int),
                     'cmx': data.seq.apply(bdm_ignore.nbdm),
                     'cmx_w': data.seq.apply(lambda x: window_bdm(x, bdm_recursive_5, k = 5))})
```


```{r data_processing}
seq7 <- as_tibble(py$seq7)
seq5 <- as_tibble(py$seq5)
seq9 <- as_tibble(py$seq9)
seq6 <- as_tibble(py$seq6)
seq8 <- as_tibble(py$seq8)


data <- select(data, -matches("^d\\d")) %>%
    filter(id %in% seq7$id) %>%
    left_join(select(seq7, id, cmx), by = "id")

seq7 <- seq7 %>%
    unnest(cols = cmx_w) %>%
    mutate(cmx_w = as.vector(cmx_w)) %>%
    group_by(id) %>%
    mutate(idx = 1:n(),
           cmx_r = rollmean(cmx_w, k = 7, align = "center", na.pad = TRUE)) %>%
    ungroup %>%
    left_join(select(data, -cmx), by = "id") %>%
    mutate(Condition = fct_relevel(as.factor(Condition), "zero")) %>%
    filter(idx < 313) %>%
    group_by(id) %>%
    mutate(cmx_wc = mean(cmx_w) - cmx_w)

seq5 <- seq5 %>%
    unnest(cols = cmx_w) %>%
    mutate(cmx_w = as.vector(cmx_w)) %>%
    group_by(id) %>%
    mutate(idx = 1:n(),
           cmx_r = rollmean(cmx_w, k = 5, align = "center", na.pad = TRUE)) %>%
    ungroup %>%
    left_join(select(data, -cmx), by = "id") %>%
    mutate(Condition = fct_relevel(as.factor(Condition), "zero")) %>%
    filter(idx < 313)  %>%
    mutate(cmx_wc = mean(cmx_w) - cmx_w)

seq9 <- seq9 %>%
    unnest(cols = cmx_w) %>%
    mutate(cmx_w = as.vector(cmx_w)) %>%
    group_by(id) %>%
    mutate(idx = 1:n(),
           cmx_r = rollmean(cmx_w, k = 9, align = "center", na.pad = TRUE)) %>%
    ungroup %>%
    left_join(select(data, -cmx), by = "id") %>%
    mutate(Condition = fct_relevel(as.factor(Condition), "zero")) %>%
    filter(idx < 313)  %>%
    mutate(cmx_wc = mean(cmx_w) - cmx_w)

seq6 <- seq6 %>%
    unnest(cols = cmx_w) %>%
    mutate(cmx_w = as.vector(cmx_w)) %>%
    group_by(id) %>%
    mutate(idx = 1:n(),
           cmx_r = rollmean(cmx_w, k = 6, align = "center", na.pad = TRUE)) %>%
    ungroup %>%
    left_join(select(data, -cmx), by = "id") %>%
    mutate(Condition = fct_relevel(as.factor(Condition), "zero")) %>%
    filter(idx < 313)  %>%
    mutate(cmx_wc = mean(cmx_w) - cmx_w)


seq8 <- seq8 %>%
    unnest(cols = cmx_w) %>%
    mutate(cmx_w = as.vector(cmx_w)) %>%
    group_by(id) %>%
    mutate(idx = 1:n(),
           cmx_r = rollmean(cmx_w, k = 8, align = "center", na.pad = TRUE)) %>%
    ungroup %>%
    left_join(select(data, -cmx), by = "id") %>%
    mutate(Condition = fct_relevel(as.factor(Condition), "zero")) %>%
    filter(idx < 313)  %>%
    mutate(cmx_wc = mean(cmx_w) - cmx_w)

```

```{r model5}
## Model selection
model5 <- lme(log(cmx_w) ~ 1 +idx*Faculty + idx*Condition,
             random = ~idx|id,
             data = seq5)
model5.4 <- update(model5,correlation = corARMA(form = ~idx|id, p = 1))
anova(model5, model5.4)
model5.5 <- update(model5.4,random = ~1|id)
anova(model5.5, model5.4)
model5.6 <- update(model5.5, random = ~idx-1|id )
anova(model5.6,model5.4)

## Errors diagnostics
par(mfrow = c(1,2))
plot(model5.4)
#qqnorm(model2,~ranef(., level = 1))
qqnorm(model5.4, abline = c(0,1))
plot(model5.4, resid(., type = 'normalized') ~ fitted(.))
plot(model5.4,resid(.,type="pearson") ~ idx,type=c("p","smooth"))
boxplot(resid(model5.4, type = 'normalized') ~ seq5$Condition)
boxplot(resid(model5.4, type = 'normalized') ~ seq5$Faculty)

## Autocorrelation Diagnostics
acf(resid(model5.4, type = 'normalized'))
pacf(resid(model5.4, type = 'normalized'))
acf(resid(model5.4))
pacf(resid(model5.4))

## Summary
r.squaredGLMM(model5.4)
summary(model5.4)
seq5 <- seq5 %>%
  mutate(predict = predict(model5.4))
```


```{r model6}
## Model specification
model6 <- lme(log(cmx_w) ~ 1 +idx*Faculty + idx*Condition,
             random = ~idx|id,
             data = seq6)
model6.4 <- update(model6,correlation = corARMA(form = ~idx|id, p=1))
anova(model6, model6.4)
model6.5 <- update(model6.4,random = ~1|id)
anova(model6.5, model6.4)
model6.6 <- update(model6.5, random = ~idx-1|id )
anova(model6.6,model6.4)

## Error Diagnostics
plot(model6.4)
#qqnorm(model2,~ranef(., level = 1))
qqnorm(model6.4, abline = c(0,1))
plot(model6.4, resid(., type = 'normalized') ~ fitted(.), type = c('p', 'smooth'))
boxplot(resid(model6.4, type = 'pearson') ~ seq6$Condition)
boxplot(resid(model6.4, type = 'pearson') ~ seq6$Faculty)

## Autocorrelation Diagnostics
acf(resid(model6.4, type = 'normalized'))
pacf(resid(model6.4, type = 'normalized'))


## Summary
r.squaredGLMM(model6.4)
summary(model6.4)
seq6 <- seq6 %>%
  mutate(predict = predict(model6.4))
```

```{r model7}
## Model Selection
model7 <- lme(log(cmx_w) ~ 1 +idx*Faculty + idx*Condition,
             random = ~idx|id,
             data = seq7)
model7.4 <- update(model7,correlation = corARMA(form = ~idx|id, p = 1))
anova(model7, model7.4)
model7.5 <- update(model7.4,random = ~1|id)
anova(model7.5, model7.4)
model7.6 <- update(model7.4, random = ~idx-1|id )
anova(model7.6,model7.4)

## Error Diagnostics
par(mfrow = c(1,2))
plot(model7.5)
#qqnorm(model2,~ranef(., level = 1))
qqnorm(model7.5, abline = c(0,1))
plot(model7.5, resid(., type = 'normalized') ~ fitted(.))
plot(model7.5,resid(.,type="pearson") ~ idx,type=c("p","smooth"))
boxplot(resid(model7.5, type = 'normalized') ~ seq7$Condition)
boxplot(resid(model7.5, type = 'normalized') ~ seq7$Faculty)

## Autocorrelation Diagnostics
acf(resid(model7.5, type = 'normalized'))
pacf(resid(model7.5, type = 'normalized'))
acf(resid(model7.5))
pacf(resid(model7.5))

## Summary
r.squaredGLMM(model7.5)
summary(model7.5)
d_cohen(model7.5)
seq7 <- seq7 %>%
  ungroup() %>%
  mutate(predict = predict(model7.5))
```

```{r model8}
## Model Selection
model8 <- lme(log(cmx_w) ~ 1 +idx*Faculty + idx*Condition,
             random = ~1|id,
             data = seq8)
model8.4 <- update(model8,correlation = corAR1(form = ~idx|id))
anova(model8, model8.4)
model8.5 <- update(model8.4,random = ~1|id)
anova(model8.5, model8.4)
model8.6 <- update(model8.5, random = ~idx-1|id )
anova(model8.6,model8.4)
model8.7 <- update(model8.5, correlation = corARMA(form = ~1|id, p = 1))

## Error Diagnostics
par(mfrow = c(1,2))
plot(model8.5)
#qqnorm(model2,~ranef(., level = 1))
qqnorm(model8.5, abline = c(0,1))
plot(model8.5, resid(., type = 'normalized') ~ fitted(.), type=c('p', 'smooth'))
plot(model8.5,resid(.,type="pearson") ~ idx,type=c("p","smooth"))
boxplot(resid(model8.5, type = 'normalized') ~ seq8$Condition)
boxplot(resid(model8.5, type = 'normalized') ~ seq8$Faculty)

## Autocorrealtion Diagnostics
acf(resid(model8.5, type = 'normalized'))
pacf(resid(model8.5, type = 'normalized'))
acf(resid(model8.7))
pacf(resid(model8.7))

## Summary
r.squaredGLMM(model8.5)
summary(model8.5)
seq8 <- seq8 %>%
  mutate(predict = predict(model8.5))
```

```{r model9}
## Model Selection
model9 <- lme(log(cmx_w) ~ 1 +idx*Faculty + idx*Condition,
             random = ~idx|id,
             data = seq9)
model9.4 <- update(model9,correlation = corARMA(form = ~idx|id, p = 1))
anova(model9, model9.4)
model9.5 <- update(model9.4,random = ~1|id)
anova(model9.5, model9.4)
model9.6 <- update(model9.5, random = ~idx-1|id )
anova(model9.6,model9.4)

## Error Diagonostics
par(mfrow = c(1,2))
plot(model9.5)
#qqnorm(model2,~ranef(., level = 1))
qqnorm(model9.5, abline = c(0,1))
plot(model9.5, resid(., type = 'normalized') ~ fitted(.))
plot(model9.5,resid(.,type="pearson") ~ idx,type=c("p","smooth"))
boxplot(resid(model9.5, type = 'normalized') ~ seq9$Condition)
boxplot(resid(model9.5, type = 'normalized') ~ seq9$Faculty)

## Autocorrelation Diagnostics
acf(resid(model9.5, type = 'normalized'))
pacf(resid(model9.5, type = 'normalized'))
acf(resid(model9.5))
pacf(resid(model9.5))

## Summary
r.squaredGLMM(model9.6)
summary(model9.5)
seq9 <- seq9 %>%
  mutate(predict = predict(model9.5))
```

```{r mean_difference_psychology_chemistry}
## Chemistry - Psychology
permutation_faculty <- permutaion_test(data = data, group_var = 'Faculty')
observed_difference <- data %>%
    group_by(Faculty) %>%
    summarise(mean = mean(cmx),
              sd = sd(cmx))
p_value(observed_difference = observed_difference, distribution = permutation_faculty)

## Coin - Zero
permutation_coin_zero <- data %>%
  filter(Condition != 'stock') %>%
  permutaion_test(data = ., group_var = 'Condition')
observed_difference <- data %>%
  filter(Condition != 'stock') %>%
  group_by(Condition) %>%
  summarise(mean = mean(cmx),
            sd = sd(cmx))
p_value(observed_difference = observed_difference, distribution = permutation_coin_zero)

## Coin - Stock
permutation_coin_stock <- data %>%
  filter(Condition != 'zero') %>%
  permutaion_test(data = ., group_var = 'Condition')
observed_difference <- data %>%
  filter(Condition != 'zero') %>%
  group_by(Condition) %>%
  summarise(mean = mean(cmx),
            sd = sd(cmx))
p_value(observed_difference = observed_difference, distribution = permutation_coin_stock)

## Stock - zero
permutation_stock_zero <- data %>%
  filter(Condition != 'coin') %>%
  permutaion_test(data = ., group_var = 'Condition')
observed_difference <- data %>%
  filter(Condition != 'coin') %>%
  group_by(Condition) %>%
  summarise(mean = mean(cmx),
            sd = sd(cmx))
p_value(observed_difference = observed_difference, distribution = permutation_stock_zero)
```
```{r contrasts}
# ## Psychology: Coin - Zero *
# permutation_coin_zero <- data %>%
#   filter(Faculty == 'psychology') %>%
#   filter(Condition != 'stock') %>%
#   permutaion_test(data = ., group_var = 'Condition')
# observed_difference <- data %>%
#   filter(Faculty == 'psychology') %>%
#   filter(Condition != 'stock') %>%
#   group_by(Condition) %>%
#   summarise(mean = mean(cmx),
#             sd = sd(cmx))
# p_value(observed_difference = observed_difference, distribution = permutation_coin_zero)
# 
# ## Psychology: Coin - Stock
# permutation_coin_stock <- data %>%
#   filter(Faculty == 'psychology') %>%
#   filter(Condition != 'zero') %>%
#   permutaion_test(data = ., group_var = 'Condition')
# observed_difference <- data %>%
#   filter(Condition != 'zero') %>%
#   group_by(Condition) %>%
#   summarise(mean = mean(cmx),
#             sd = sd(cmx))
# p_value(observed_difference = observed_difference, distribution = permutation_coin_stock)
# 
# ## Psychology: Stock - zero
# permutation_stock_zero <- data %>%
#   filter(Faculty == 'psychology') %>%
#   filter(Condition != 'coin') %>%
#   permutaion_test(data = ., group_var = 'Condition')
# observed_difference <- data %>%
#   filter(Condition != 'coin') %>%
#   group_by(Condition) %>%
#   summarise(mean = mean(cmx),
#             sd = sd(cmx))
# p_value(observed_difference = observed_difference, distribution = permutation_stock_zero)
# 
# ## Chemistry: Coin - Zero
# permutation_coin_zero <- data %>%
#   filter(Faculty == 'chemistry') %>%
#   filter(Condition != 'stock') %>%
#   permutaion_test(data = ., group_var = 'Condition')
# observed_difference <- data %>%
#   filter(Faculty == 'chemistry') %>%
#   filter(Condition != 'stock') %>%
#   group_by(Condition) %>%
#   summarise(mean = mean(cmx),
#             sd = sd(cmx))
# p_value(observed_difference = observed_difference, distribution = permutation_coin_zero)
# 
# ## Chemistry: Coin - Stock
# permutation_coin_stock <- data %>%
#   filter(Faculty == 'chemistry') %>%
#   filter(Condition != 'zero') %>%
#   permutaion_test(data = ., group_var = 'Condition')
# observed_difference <- data %>%
#   filter(Faculty == 'chemistry') %>%
#   filter(Condition != 'zero') %>%
#   group_by(Condition) %>%
#   summarise(mean = mean(cmx),
#             sd = sd(cmx))
# p_value(observed_difference = observed_difference, distribution = permutation_coin_stock)
# 
# ## Chemistry: Stock - zero *
# permutation_stock_zero <- data %>%
#   filter(Faculty == 'chemistry') %>%
#   filter(Condition != 'coin') %>%
#   permutaion_test(data = ., group_var = 'Condition')
# observed_difference <- data %>%
#   filter(Faculty == 'chemistry') %>%
#   filter(Condition != 'coin') %>%
#   group_by(Condition) %>%
#   summarise(mean = mean(cmx),
#             sd = sd(cmx))
# p_value(observed_difference = observed_difference, distribution = permutation_stock_zero)
```

```{r contrast_faculty}
# ## Chemistry - Psychology: coin
# permutation_faculty <- data %>%
#   filter(Condition == 'coin') %>%
#   permutaion_test(data = ., group_var = 'Faculty')
# observed_difference <- data %>%
#   filter(Condition == 'coin') %>%
#   group_by(Faculty) %>%
#   summarise(mean = mean(cmx),
#               sd = sd(cmx))
# p_value(observed_difference = observed_difference, distribution = permutation_faculty)
# 
# ## Chemistry - Psychology: stock
# permutation_faculty <- data %>%
#   filter(Condition == 'stock') %>%
#   permutaion_test(data = ., group_var = 'Faculty')
# observed_difference <- data %>%
#   filter(Condition == 'stock') %>%
#   group_by(Faculty) %>%
#   summarise(mean = mean(cmx),
#               sd = sd(cmx))
# p_value(observed_difference = observed_difference, distribution = permutation_faculty)
# 
# ## Chemistry - Psychology: zero
# permutation_faculty <- data %>%
#   filter(Condition == 'zero') %>%
#   permutaion_test(data = ., group_var = 'Faculty')
# observed_difference <- data %>%
#   filter(Condition == 'zero') %>%
#   group_by(Faculty) %>%
#   summarise(mean = mean(cmx),
#               sd = sd(cmx))
# p_value(observed_difference = observed_difference, distribution = permutation_faculty)

```

### Study 2.

```{r load_and_prepare_data2}
data2 <- read_sav("data/Study_2.sav") %>%
  mutate(id = 1:n()) %>%
  select(-Id) %>%
  filter(survey_finish_time >= 656 & survey_finish_time < 1708) %>%
  rename_at(vars(matches("^v1_r\\d+")),
            ~str_extract(string = .x, pattern = '\\d+$') %>%
              str_c("pzp", .)) %>%
  rename_at(vars(matches("^v2_r\\d+")),
            ~str_extract(string = .x, pattern = '\\d+$') %>%
              str_c('pp', .)) %>%
  mutate_at(vars(matches("pp\\d+")), ~as.numeric(.)) %>%
  mutate_at(vars(matches("pzp\\d+")), ~as.numeric(.))
```

```{r tests_calculations}
data2 <- data2 %>%
  mutate_at(vars(matches("pp[2, 3, 8, 10, 13, 15, 17, 19, 22, 26, 28, 33, 34, 35]")), ~{6-.}) %>%
  mutate_at(vars(matches("pzp[2, 5, 10, 14, 15, 16, 17, 18, 20, 24, 30, 31]")), ~{7-.}) %>%
  mutate(year = as.numeric(year)) %>%
  select(-age) %>%
  rowwise() %>%
  mutate(preferowanie_porzadku = sum(pzp1, pzp6, pzp17, pzp19, pzp26, pzp27, pzp28),
         preferowanie_przewidywalnosci = sum(pzp5, pzp7, pzp9, pzp15, pzp16, pzp21, pzp22, pzp32),
         nietolerowanie_wieloznacznosci = sum(pzp3, pzp8, pzp12, pzp24, pzp25, pzp29),
         zamknietosc_umyslowa = sum(pzp2, pzp4, pzp20, pzp23, pzp30, pzp31),
         zdecydowanie = sum(pzp10, pzp11, pzp13, pzp14, pzp18),
         preferowanie_porzadku2 = sum(pzp6, pzp26, pzp27),
         preferowanie_przewidywalnosci2 = sum(pzp9, pzp21, pzp32),
         nietolerowanie_wieloznacznosci2 = sum(pzp3, pzp8, pzp29),
         zamknietosc_umyslowa2 = sum(pzp2, pzp20, pzp31),
         zdecydowanie2 = sum(pzp13, pzp14, pzp18),
         potrzeba_poznania = sum(pp1, pp2, pp3, pp4, pp5, pp6, pp7, pp8, pp9, pp10,
                                 pp11, pp12, pp13, pp14, pp15, pp16, pp17, pp18, pp19, pp20,
                                 pp21, pp22, pp23, pp24, pp25, pp26, pp27, pp28, pp29, pp30,
                                 pp31, pp32, pp33, pp34, pp35, pp36),
         warunek = as.character(warunek),
         warunek = if_else(warunek == "1", "homogeneous", "heterogeneous")) %>%
  select(-matches('pp\\d+|pzp\\d+'))

data2_time <- data2 %>%
  gather(key = "Index", value = "Bit", matches("war[[:digit:]]")) %>%
  filter(!is.na(Bit)) %>% 
  filter(Bit != 99) %>% 
  mutate(klucz = if_else(grepl(x = Index, pattern = "time"), 'time', 'seq'),
         ids = str_extract(Index, pattern = '^war1_\\d+|^war2g\\d+_|^war2rm\\d+_'),
         ids = if_else(grepl(x = ids, pattern = 'war1'),
                       str_extract(string = ids, pattern = '(\\d+)(?!.*\\d)'),
                       str_extract(string = ids, pattern = '([rmg]+\\d+)(?!.*\\d)')),
         ids = case_when(ids == 'rm1' ~ '1',
                         ids == 'g1' ~ '2',
                         ids == 'rm2' ~ '3',
                         ids == 'g2' ~ '4',
                         ids == 'rm3' ~ '5',
                         ids == 'g3' ~ '6',
                         ids == 'rm4' ~ '7',
                         ids == 'g4' ~ '8',
                         ids == 'rm5' ~ '9',
                         ids == 'g5' ~ '10',
                         TRUE ~ ids),
         ids = as.numeric(ids)) %>%
  select(id, ids, Bit, klucz) %>%
  group_by(id, ids, klucz) %>%
  mutate(idx = 1:n()) %>%
  spread(klucz, Bit) %>%
  filter(!is.na(seq))

data2_long <- data2_time %>%
  select(id, ids, seq) %>%
  group_by(id, ids) %>%
  summarise(seq = list(seq)) %>%
  filter(lengths(seq)>8)
```

```{python prepare_strings2}
import numpy as np
import pandas as pd
from pybdm import BDM
from pybdm import PartitionIgnore, PartitionRecursive
    
def window_bdm(seq, bdm, k=7):
    return np.array([ bdm.bdm(seq[i:(i+k)]) for i in range(len(seq) - k) ])
    
data = r.data2_long
data.id = data.id.astype(int)
data.ids = data.ids.astype(int)
data.seq = data.seq.apply(lambda x: np.array(x, dtype=int))


bdm_recursive_7 = BDM(ndim=1, partition=PartitionRecursive, min_length=7)
seq7 = pd.DataFrame({'id': r.data2_long.id.astype(int),
                     'ids': r.data2_long.ids.astype(int),
                     'cmx': data.seq.apply(bdm_recursive_7.nbdm),
                     'cmx_w': data.seq.apply(lambda x: window_bdm(x, bdm_recursive_7, k=7))})

bdm_recursive_5 = BDM(ndim=1, partition=PartitionRecursive, min_length=5)
seq5 = pd.DataFrame({'id': r.data2_long.id.astype(int),
                     'ids': r.data2_long.ids.astype(int),
                     'cmx': data.seq.apply(bdm_recursive_5.nbdm),
                     'cmx_w': data.seq.apply(lambda x: window_bdm(x, bdm_recursive_5, k=5))})

bdm_recursive_6 = BDM(ndim=1, partition=PartitionRecursive, min_length=6)
seq6 = pd.DataFrame({'id': r.data2_long.id.astype(int),
                     'ids': r.data2_long.ids.astype(int),
                     'cmx': data.seq.apply(bdm_recursive_6.nbdm),
                     'cmx_w': data.seq.apply(lambda x: window_bdm(x, bdm_recursive_6, k=6))})

bdm_recursive_8 = BDM(ndim=1, partition=PartitionRecursive, min_length=8)
seq8 = pd.DataFrame({'id': r.data2_long.id.astype(int),
                     'ids': r.data2_long.ids.astype(int),
                     'cmx': data.seq.apply(bdm_recursive_8.nbdm),
                     'cmx_w': data.seq.apply(lambda x: window_bdm(x, bdm_recursive_8, k=8))})
                     
bdm_recursive_9 = BDM(ndim=1, partition=PartitionRecursive, min_length=9)
seq9 = pd.DataFrame({'id': r.data2_long.id.astype(int),
                     'ids': r.data2_long.ids.astype(int),
                     'cmx': data.seq.apply(bdm_recursive_9.nbdm),
                     'cmx_w': data.seq.apply(lambda x: window_bdm(x, bdm_recursive_9, k=9))})
```


```{r prepare_data_for_models}
seq5 <- py$seq5
seq6 <- py$seq6
seq7 <- py$seq7
seq8 <- py$seq8
seq9 <- py$seq9

data2 <- data2_long %>%
  select(id, ids) %>%
  left_join(data2) %>%
  left_join(seq7 %>% select(id, ids,cmx)) %>%
  select(-matches('war\\d.')) %>%
  left_join(data2_time %>% select(id, ids, idx, time) %>% group_by(id,ids) %>% summarise(time = sum(time)))
  
seq5 <- seq5 %>%
    unnest(cols = cmx_w) %>%
    mutate(cmx_w = as.vector(cmx_w)) %>% 
    group_by(id,ids) %>%
    mutate(idx = 1:n()) %>%
    ungroup %>%
    left_join(select(data2, -cmx)) %>%
    left_join(data2_time %>%
               select(id, idx, ids, idx_time = time) %>%
               mutate(time_roll = rollsum(idx_time, k =5, align = "left", fill = NA)) %>%
               filter(!is.na(time_roll)) %>%
                select(id, idx, ids, time_roll))

seq6 <- seq6 %>%
    unnest(cols = cmx_w) %>%
    mutate(cmx_w = as.vector(cmx_w)) %>% 
    group_by(id,ids) %>%
    mutate(idx = 1:n()) %>%
    ungroup %>%
    left_join(select(data2, -cmx)) %>%
  left_join(data2_time %>%
               select(id, idx, ids, idx_time = time) %>%
               mutate(time_roll = rollsum(idx_time, k =6, align = "left", fill = NA)) %>%
               filter(!is.na(time_roll)) %>%
               select(id, idx, ids, time_roll))


seq7 <- seq7 %>%
    unnest(cols = cmx_w) %>%
    mutate(cmx_w = as.vector(cmx_w)) %>% 
    group_by(id,ids) %>%
    mutate(idx = 1:n()) %>%
    ungroup %>%
    left_join(select(data2, -cmx)) %>%
  left_join(data2_time %>%
               select(id, idx, ids, idx_time = time) %>%
               mutate(time_roll = rollsum(idx_time, k = 7, align = "left", fill = NA)) %>%
               filter(!is.na(time_roll)) %>%
               select(id, idx, ids, time_roll))

seq8 <- seq8 %>%
    unnest(cols = cmx_w) %>%
    mutate(cmx_w = as.vector(cmx_w)) %>% 
    group_by(id,ids) %>%
    mutate(idx = 1:n()) %>%
    ungroup %>%
    left_join(select(data2, -cmx)) %>%
  left_join(data2_time %>%
               select(id, idx, ids, idx_time = time) %>%
               mutate(time_roll = rollsum(idx_time, k =8, align = "left", fill = NA)) %>%
               filter(!is.na(time_roll)) %>%
               select(id, idx, ids, time_roll))

seq9 <- seq9 %>%
    unnest(cols = cmx_w) %>%
    mutate(cmx_w = as.vector(cmx_w)) %>% 
    group_by(id,ids) %>%
    mutate(idx = 1:n()) %>%
    ungroup %>%
    left_join(select(data2, -cmx)) %>%
  left_join(data2_time %>%
               select(id, idx, ids, idx_time = time) %>%
               mutate(time_roll = rollsum(idx_time, k =9, align = "left", fill = NA)) %>%
               filter(!is.na(time_roll)) %>%
               select(id, idx, ids, time_roll))

```

```{r model_all}
model <- lme(cmx ~ 1 + (ids)*warunek +
               preferowanie_porzadku2 +
               preferowanie_przewidywalnosci2 +
               nietolerowanie_wieloznacznosci2 +
               zamknietosc_umyslowa2 +
               potrzeba_poznania +
               survey_finish_time,
             random = ~ids|id,
             data = data2,
             correlation = corCAR1(form = ~ids|id), method = "ML")

model2 <- update(model, random = ~ids-1|id )
anova(model,model2)
model3 <- update(model, random = ~1|id)
anova(model,model3)

## Error Diagnostics
plot(model)
#qqnorm(model2,~ranef(., level = 1))
qqnorm(model2, abline = c(0,1))
plot(model, resid(., type = 'normalized') ~ fitted(.), type = c("p", "smooth"))
plot(model,resid(.,type="pearson") ~ (ids),type=c("p","smooth"))
plot(model,resid(.,type="pearson") ~ survey_finish_time,type=c("p","smooth"))
plot(model,resid(.,type="pearson") ~ preferowanie_porzadku2,type=c("p","smooth"))
plot(model,resid(.,type="pearson") ~ preferowanie_przewidywalnosci2,type=c("p","smooth"))
plot(model,resid(.,type="pearson") ~ nietolerowanie_wieloznacznosci2,type=c("p","smooth"))
plot(model,resid(.,type="pearson") ~ zamknietosc_umyslowa2,type=c("p","smooth"))
plot(model,resid(.,type="pearson") ~ potrzeba_poznania,type=c("p","smooth"))
#plot(model,resid(.,type="pearson") ~ year,type=c("p","smooth"))
boxplot(resid(model, type = 'normalized') ~ data2$warunek)

model_quadratic <- lme(cmx ~ 1 +ids*warunek + I(ids^2)*warunek +
               preferowanie_porzadku2 +
               preferowanie_przewidywalnosci2 +
               nietolerowanie_wieloznacznosci2 +
               zamknietosc_umyslowa2 +
               potrzeba_poznania,
             random = ~ids|id,
             data = data2,
             correlation = corCAR1(form = ~ids|id),
             method = "ML")

anova(model_quadratic, model)

model2 <- update(model_quadratic, random = ~ids-1|id )
anova(model_quadratic,model2)
model3 <- update(model_quadratic, random = ~1|id)
anova(model_quadratic,model3)

## Error Diagnostics
plot(model_quadratic)
#qqnorm(model2,~ranef(., level = 1))
qqnorm(model_quadratic, abline = c(0,1))
plot(model_quadratic, resid(., type = 'normalized') ~ fitted(.), type = c("p", "smooth"))
plot(model_quadratic,resid(.,type="pearson") ~ (ids),type=c("p","smooth"))
plot(model_quadratic,resid(.,type="pearson") ~ survey_finish_time,type=c("p","smooth"))
plot(model_quadratic,resid(.,type="pearson") ~ preferowanie_porzadku2,type=c("p","smooth"))
plot(model_quadratic,resid(.,type="pearson") ~ preferowanie_przewidywalnosci2,type=c("p","smooth"))
plot(model_quadratic,resid(.,type="pearson") ~ nietolerowanie_wieloznacznosci2,type=c("p","smooth"))
plot(model_quadratic,resid(.,type="pearson") ~ zamknietosc_umyslowa2,type=c("p","smooth"))
plot(model_quadratic,resid(.,type="pearson") ~ potrzeba_poznania,type=c("p","smooth"))
#plot(model,resid(.,type="pearson") ~ year,type=c("p","smooth"))
boxplot(resid(model_quadratic, type = 'normalized') ~ data2$warunek)

## Autocorrealtion Diagnostics
acf(resid(model_quadratic, type = 'normalized'))
pacf(resid(model_quadratic, type = 'normalized'))

## Summary
r.squaredGLMM(model_quadratic)
summary(model_quadratic)
```

```{r model52}
## Model selection
model5 <- lme(log(cmx_w) ~ 1 + idx*ids*warunek +
               log(time_roll),
             random = ~1|idx + idx|ids + ids|id,
             weights = varIdent(~warunek),
             data = seq5,
             correlation = corCAR1(form = ~1|id))
model5.5 <- update(model5,random = ~1|id)
anova(model5, model5.5)
model5.6 <- update(model5.5, random = ~idx-1|id )
anova(model5.6,model5)

## Error Diagnostics
plot(model5.5)
#qqnorm(model2,~ranef(., level = 1))
qqnorm(model5.5, abline = c(0,1))
plot(model5.5, resid(., type = 'normalized') ~ fitted(.), type = c("p", "smooth"))
plot(model5.5,resid(.,type="pearson") ~ (ids),type=c("p","smooth"))
plot(model5.5,resid(.,type="pearson") ~ log(time_roll),type=c("p","smooth"))
boxplot(resid(model5.5, type = 'normalized') ~ seq5$warunek)

## Autocorrealtion Diagnostics
acf(resid(model5, type = 'normalized'))
pacf(resid(model5, type = 'normalized'))

## Summary
r.squaredGLMM(model5)
summary(model5)
``` 
```{r model62}
## Model selection
model6 <- lme(log(cmx_w) ~ 1 + idx*(ids)*warunek +
               log(time_roll),
             random = ~1|idx+idx|ids+ids|id,
             weights = varIdent(~warunek),
             data = seq6,
             correlation = corCAR1(form = ~1|id))

model6.5 <- update(model6,random = ~1|id)
anova(model6, model6.5)
model6.6 <- update(model6, random = ~idx-1|id )
anova(model6.6,model6)

## Error Diagnostics
plot(model6.5)
#qqnorm(model2,~ranef(., level = 1))
qqnorm(model6.5, abline = c(0,1))
plot(model6.5, resid(., type = 'normalized') ~ fitted(.), type = c("p", "smooth"))
plot(model6.5,resid(.,type="pearson") ~ log(time_roll),type=c("p","smooth"))
plot(model6.5,resid(.,type="pearson") ~ (ids),type=c("p","smooth"))
plot(model6.5,resid(.,type="pearson") ~ idx,type=c("p","smooth"))
#plot(model,resid(.,type="pearson") ~ year,type=c("p","smooth"))
boxplot(resid(model6.5, type = 'normalized') ~ seq6$warunek)

## Autocorrealtion Diagnostics
acf(resid(model6.5, type = 'normalized'))
pacf(resid(model6.5, type = 'normalized'))

## Summary
r.squaredGLMM(model6.5)
summary(model6.5)
``` 
```{r model72}
## Model selection
model7 <- lme(log(cmx_w) ~ 1 + idx*(ids)*warunek +
               log(time_roll),
             random = ~1|idx + idx|ids+ids|id,
             data = seq7,
             correlation = corCAR1(form = ~1|id))

model7.5 <- update(model7,random = ~1|id)
anova(model7, model7.5)
model7.6 <- update(model7.5, random = ~idx-1|id )
anova(model7.6,model7)

## Error Diagnostics
plot(model7.5)
#qqnorm(model2,~ranef(., level = 1))
qqnorm(model7.5, abline = c(0,1))
plot(model7.5, resid(., type = 'normalized') ~ fitted(.), type = c("p", "smooth"))
plot(model7.5,resid(.,type="pearson") ~ (ids),type=c("p","smooth"))
plot(model7.5,resid(.,type="pearson") ~ (idx),type=c("p","smooth"))
plot(model7.5,resid(.,type="pearson") ~ log(time_roll),type=c("p","smooth"))
boxplot(resid(model7.5, type = 'normalized') ~ seq7$warunek)

## Autocorrealtion Diagnostics
acf(resid(model7.5, type = 'normalized'))
pacf(resid(model7.5, type = 'normalized'))

## Summary
r.squaredGLMM(model7.5)
summary(model7.5)
``` 
 
```{r model82}
## Model selection
model8 <- lme(log(cmx_w) ~ 1 + idx*(ids)*warunek +
               log(time_roll),
             random = ~1|idx+idx|ids+ids|id,
             data = seq8,
             correlation = corCAR1(form = ~1|id))

model8.5 <- update(model8,random = ~1|id)
anova(model8, model8.5)
model8.6 <- update(model8.5, random = ~idx-1|id )
anova(model8.6,model8)

## Error Diagnostics
plot(model8.5)
#qqnorm(model2,~ranef(., level = 1))
qqnorm(model8.5, abline = c(0,1))
plot(model8.5, resid(., type = 'normalized') ~ fitted(.), type = c("p", "smooth"))
plot(model8.5,resid(.,type="pearson") ~ (ids),type=c("p","smooth"))
plot(model8.5,resid(.,type="pearson") ~ (idx),type=c("p","smooth"))
plot(model8.5,resid(.,type="pearson") ~ log(time_roll),type=c("p","smooth"))

#plot(model,resid(.,type="pearson") ~ year,type=c("p","smooth"))
boxplot(resid(model8.5, type = 'normalized') ~ seq8$warunek)

## Autocorrealtion Diagnostics
acf(resid(model8.5, type = 'normalized'))
pacf(resid(model8.5, type = 'normalized'))

## Summary
r.squaredGLMM(model8.5)
summary(model8.5)
``` 
```{r model92}
## Model selection
model9 <- lme(log(cmx_w) ~ 1 + idx*(ids)*warunek +
               log(time_roll),
             random = ~1|idx+idx|ids+ids|id,
             data = seq9,
             correlation = corCAR1(form = ~1|id))

model9.5 <- update(model9,random = ~1|id)
anova(model9, model9.5)
model9.6 <- update(model9.5, random = ~idx-1|id )
anova(model9.6,model9)

## Error Diagnostics
plot(model9.5)
#qqnorm(model2,~ranef(., level = 1))
qqnorm(model9.5, abline = c(0,1))
plot(model9.5, resid(., type = 'normalized') ~ fitted(.), type = c("p", "smooth"))
plot(model9.5,resid(.,type="pearson") ~ (ids),type=c("p","smooth"))
plot(model9.5,resid(.,type="pearson") ~ (idx),type=c("p","smooth"))
plot(model9.5,resid(.,type="pearson") ~ log(time_roll),type=c("p","smooth"))
#plot(model,resid(.,type="pearson") ~ year,type=c("p","smooth"))
boxplot(resid(model9.5, type = 'normalized') ~ seq9$warunek)

## Autocorrealtion Diagnostics
acf(resid(model9.5, type = 'normalized'))
pacf(resid(model9.5, type = 'normalized'))

## Summary
r.squaredGLMM(model9.5)
summary(model9.5)
``` 
